### ISSUE TITLE
how to use the code

### ISSUE THREAD

**Issue by candybetterbest** [nklayman/ca-dmv-poller#2]
Hi, Thank you so much for the new code, I'm newbie here, wondering if you could advise how to use your file. I've installed npm.

**Comment by nklayman** [comment]
This code provides an API for accessing the DMV's website. You will have to create a ui or other frontend that makes use of the api. [This app](https://play.google.com/store/apps/details?id=com.f12devs.CaDmvAppointmentFastFinder) does that. If you need a windows/linux version, I can send you that as well.
