### ISSUE TITLE
Steps to run use this code

### ISSUE THREAD

**Issue by angudadev** [nklayman/ca-dmv-poller#4]
Hi Nklayman, 

please provide the steps to run this code. 

Thanks,
Anurag G

**Comment by nklayman** [comment]
Added a README, thanks for the reminder.

**Comment by angudadev** [comment]
When i try to install ca-dmv-poller modules it's throwing below error. could you please let me know how can i proceed with this. Thanks in advance. 


npm install ca-dmv-poller
npm ERR! Linux 3.10.0-693.17.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "ca-dmv-poller"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

**npm ERR! Refusing to install ca-dmv-poller as a dependency of itself**
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/dmv/ca-dmv-poller/npm-debug.log

Thanks,
Anurag G
