### ISSUE TITLE
Make appointment page as a result instead of available date

### ISSUE THREAD

**Issue by Hellaren** [nklayman/ca-dmv-poller#7]
Hey, I followed the instruction in readme to this project and have a problem with getting available dates.
I received "unknown" result for every office. I modified the script in order to see the result from server and here it is:
[log.txt](https://github.com/nklayman/ca-dmv-poller/files/3025131/log.txt)

Looks like the poller downloads "Make appointment" page instead of result page.
I see that the latest commit was made almost a month ago, want to make sure that it is still working.

Thank you

**Comment by nklayman** [comment]
If you view the rendered page, you'll see that it loaded the appointment page again because there was missing information:
![image](https://user-images.githubusercontent.com/12448243/55279815-35c59480-52da-11e9-8897-f9516f156ec0.png)
If the information is correct, it should load the results page instead of the form page.

**Comment by Hellaren** [comment]
I tried to run the same script you provided in readme and received the same error.
Here is the script (changed distance to 3 and commented coords and address):
`const Poller = require('ca-dmv-poller')

const poller = new Poller({
  itemsToProcess: 1, // Number of items user would like to process
  maxDistanceMiles: 3, // Distance from home location to search for DMV Offices

  // Provide zipCode, coords, or address
  zipCode: '95630', // or
  // coords: {
  //   lat: '38.733792',
  //   lng: '-121.141315'
  // } // or
  // address: '1600 Amphitheatre Pkwy, Mountain View, CA 94043',

  mode: 'OfficeVisit', // or 'DriveTest'
  // CID: Apply for, replace, or renew a California DL/ID
  // RID: Apply for, replace, or renew a REAL ID
  // VR: Register or title a vehicle or vessel (boat)
  appointmentTypes: ['CID'],
  // User's appointment information
  appointmentInfo: {
    appointmentInfo: {
      firstName: 'John',
      lastName: 'Doe',
      telArea: '123',
      telPrefix: '456',
      telSuffix: '7890',
      birthDay: '01',
      birthMonth: '01',
      birthYear: '2001',
      dlNumber: 'I0004567', // AKA Permit Number
      requestedTask: 'DT', // (automobile) or 'MC' (motorcycle),
      safetyCourseCompletedSelection: 'TRUE' // or 'FALSE', motorcycle test only
    }
  }
})

poller
  .check()
  .then(results => {
    results.forEach(result => {
      if (result.hasFailed) {
        console.log(
          result.response
        )
        return
      }
      console.log('Day of appointment: ', result.date)
      console.log('Days until appointment: ', result.daysUntil)
      console.log('Location of appointment: ', result.location)
    })
  })
  .catch(e => console.error(e))`

To run this code I use ts-node. May be this is the reason?
What is the preferred way to run it?

**Comment by nklayman** [comment]
My bad, the example was incorrect (`appointmentInfo` was nested inside another `appoinmentInfo` key). I updated the README with the correct example, use that instead. Thanks for reporting the issue!

**Comment by Hellaren** [comment]
Works like a charm, thank you!
